version: '3.6'

networks:
  default:
    name: ${PROJECT_NAME}
    ipam:
      config:
        - subnet: ${SUBNET}

services:
  php:
    build: docker/php
    container_name: "${PROJECT_NAME}_php"
    depends_on:
      - mariadb
      - postgres
    volumes:
      - ./:/var/www

  mariadb:
    build: docker/mariadb
    container_name: "${PROJECT_NAME}_mariadb"
    ports:
      - "${LOCALHOST_MARIADB_PORT}:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ${VOLUMES_DIR}/mariadb:/var/lib/mysql

  postgres:
    build: docker/postgres
    container_name: "${PROJECT_NAME}_postgres"
    ports:
      - "${LOCALHOST_POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS}
      - POSTGRES_USER=${POSTGRES_DB_USER}
    volumes:
      - ${VOLUMES_DIR}/postgres:/var/lib/postgresql/data

  nginx:
    container_name: "${PROJECT_NAME}_nginx"
    build: docker/nginx
    ports:
      - "${LOCALHOST_HTTP_PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ${VOLUMES_DIR}/log:/var/log
    depends_on:
      - php
